export const bggToSimplifiedMechanics = {
  "Worker Placement": "Worker Placement",
  "Worker Placement with Dice Workers": "Worker Placement",
  "Worker Placement, Different Worker Types": "Worker Placement",
  "Automatic Resource Growth": "Engine Building",
  "Chaining": "Engine Building",
  "Tech Trees / Tech Tracks": "Engine Building",
  "Income": "Engine Building",
  "Multi-Use Cards": "Engine Building",
  "Resource to Move": "Resource Management",
  "Resource Queue": "Resource Management",
  "Victory Points as a Resource": "Resource Management",
  "Advantage Token": "Resource Management",
  "Trading": "Economic/Trading",
  "Commodity Speculation": "Economic/Trading",
  "Market": "Economic/Trading",
  "Investment": "Economic/Trading",
  "Loans": "Economic/Trading",
  "Stock Holding": "Economic/Trading",
  "Ownership": "Economic/Trading",
  "Deck, Bag, and Pool Building": "Deck Building",
  "Deck Construction": "Deck Building",
  "Hand Management": "Hand Management",
  "Melding and Splaying": "Hand Management",
  "Action Drafting": "Card Drafting",
  "Open Drafting": "Card Drafting",
  "Closed Drafting": "Card Drafting",
  "Trick-taking": "Trick-Taking",
  "Dice Rolling": "Dice Rolling",
  "Die Icon Resolution": "Dice Rolling",
  "Different Dice Movement": "Dice Rolling",
  "Critical Hits and Failures": "Dice Rolling",
  "Cube Tower": "Dice Rolling",
  "Push Your Luck": "Push Your Luck",
  "Bids As Wagers": "Push Your Luck",
  "Hot Potato": "Push Your Luck",
  "Re-rolling and Locking": "Dice Manipulation",
  "Tile Placement": "Tile Placement",
  "Map Addition": "Tile Placement",
  "Map Deformation": "Tile Placement",
  "Map Reduction": "Tile Placement",
  "Area Majority / Influence": "Area Control",
  "King of the Hill": "Area Control",
  "Enclosure": "Area Control",
  "Zone of Control": "Area Control",
  "Grid Movement": "Grid Movement",
  "Square Grid": "Grid Movement",
  "Hexagon Grid": "Grid Movement",
  "Grid Coverage": "Grid Movement",
  "Network and Route Building": "Network Building",
  "Connections": "Network Building",
  "Crayon Rail System": "Network Building",
  "Line Drawing": "Network Building",
  "Pattern Building": "Pattern Building",
  "Layering": "Pattern Building",
  "Action Points": "Action Points",
  "Movement Points": "Action Points",
  "Variable Player Powers": "Variable Player Powers",
  "Roles with Asymmetric Information": "Variable Player Powers",
  "Simultaneous Action Selection": "Simultaneous Action Selection",
  "Programmed Movement": "Programmed Actions",
  "Action Queue": "Programmed Actions",
  "Pattern Movement": "Programmed Actions",
  "Deduction": "Deduction",
  "Induction": "Deduction",
  "Targeted Clues": "Deduction",
  "Hidden Roles": "Hidden Roles",
  "Traitor Game": "Hidden Roles",
  "Secret Unit Deployment": "Hidden Roles",
  "Betting and Bluffing": "Bluffing",
  "Cooperative Game": "Cooperative",
  "Communication Limits": "Cooperative",
  "Team-Based Game": "Team-Based",
  "Alliances": "Team-Based",
  "Semi-Cooperative Game": "Semi-Cooperative",
  "Set Collection": "Set Collection",
  "Matching": "Set Collection",
  "Pattern Recognition": "Pattern Recognition",
  "Speed Matching": "Pattern Recognition",
  "Contracts": "Contracts",
  "Auction / Bidding": "Auction/Bidding",
  "Auction Compensation": "Auction/Bidding",
  "Auction: Dexterity": "Auction/Bidding",
  "Auction: Dutch": "Auction/Bidding",
  "Auction: Dutch Priority": "Auction/Bidding",
  "Auction: English": "Auction/Bidding",
  "Auction: Fixed Placement": "Auction/Bidding",
  "Auction: Multiple Lot": "Auction/Bidding",
  "Auction: Once Around": "Auction/Bidding",
  "Auction: Sealed Bid": "Auction/Bidding",
  "Auction: Turn Order Until Pass": "Auction/Bidding",
  "Closed Economy Auction": "Auction/Bidding",
  "Constrained Bidding": "Auction/Bidding",
  "Selection Order Bid": "Auction/Bidding",
  "Predictive Bid": "Auction/Bidding",
  "Turn Order: Auction": "Auction/Bidding",
  "Negotiation": "Negotiation",
  "Bribery": "Negotiation",
  "I Cut, You Choose": "Negotiation",
  "Voting": "Negotiation",
  "Prisoner's Dilemma": "Negotiation",
  "Card Play Conflict Resolution": "Combat",
  "Ratio / Combat Results Table": "Combat",
  "Stat Check Resolution": "Combat",
  "Force Commitment": "Combat",
  "Tug of War": "Combat",
  "Kill Steal": "Combat",
  "Take That": "Take That",
  "Physical Removal": "Take That",
  "Static Capture": "Take That",
  "Legacy Game": "Legacy",
  "Scenario / Mission / Campaign Game": "Campaign/Scenario",
  "Campaign / Battle Card Driven": "Campaign/Scenario",
  "Storytelling": "Narrative",
  "Narrative Choice / Paragraph": "Narrative",
  "Role Playing": "Narrative",
  "Hidden Movement": "Hidden Movement",
  "Real-Time": "Real-Time",
  "Action Timer": "Real-Time",
  "Flicking": "Dexterity",
  "Stacking and Balancing": "Dexterity",
  "Spelling": "Word Games",
  "Paper-and-Pencil": "Paper and Pencil",
  "Ladder Climbing": "Ladder Climbing",
  // "Solo / Solitaire Game": "Solo"
}